export const DELETE_PROFILE = 'profiles/DELETE_PROFILE';
export const DELETE_PROFILE_SUCCESS = 'profiles/DELETE_PROFILE_SUCCESS';

export const CREATE_PROFILE = 'profiles/CREATE_PROFILE';
export const CREATE_PROFILE_SUCCESS = 'profiles/CREATE_PROFILE_SUCCESS';

export const EDIT_PROFILE = 'profiles/EDIT_PROFILE';
export const EDIT_PROFILE_SUCCESS = 'profiles/EDIT_PROFILE_SUCCESS';

export const LOAD_PROFILES = 'profiles/LOAD_PROFILES';
export const LOAD_PROFILES_SUCCESS = 'profiles/LOAD_PROFILES_SUCCESS';

export default {
    DELETE_PROFILE,
    DELETE_PROFILE_SUCCESS,
    CREATE_PROFILE,
    CREATE_PROFILE_SUCCESS,
    EDIT_PROFILE,
    EDIT_PROFILE_SUCCESS,
    LOAD_PROFILES,
    LOAD_PROFILES_SUCCESS
};
